{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "79931b7f-ec44-428d-8037-8f9b17579d3a",
   "metadata": {},
   "source": [
    "554 Project 3\n",
    "\n",
    "by Joshua McClure"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1d78a8fa-aaf3-46af-8da1-6aeb11de459b",
   "metadata": {},
   "source": [
    "Fitting Your Model (50 pts)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a44bd3fe-ffa4-45e6-9d7d-7e1adf681d6b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Library for Packages\n",
    "import pandas as pd\n",
    "import time\n",
    "import os\n",
    "from pyspark.ml import Pipeline\n",
    "from pyspark.sql import SparkSession\n",
    "from pyspark.sql.types import StructType, StructField, DoubleType, StringType, IntegerType\n",
    "from pyspark.ml.feature import SQLTransformer, Binarizer, StringIndexer, OneHotEncoder, VectorAssembler, PCA\n",
    "from pyspark.ml.regression import LinearRegression\n",
    "from pyspark.ml.tuning import ParamGridBuilder, CrossValidator\n",
    "from pyspark.ml.evaluation import RegressionEvaluator\n",
    "from pyspark.sql.functions import col"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c8e256c3-44d4-48fb-aff8-dda2d9f2854c",
   "metadata": {},
   "source": [
    "Part 1: Read in and Organize Data\n",
    "\n",
    "Create a Jupyter notebook for the modeling fitting part and the Streaming part below.\n",
    "\n",
    "* The file power_ml_data.csv is available at the URL: https://www4.stat.ncsu.edu/~online/datasets/ power_ml_data.csv\n",
    "\n",
    "* You should read this data into a standard pandas data frame using the pd.read_csv() function.\n",
    "\n",
    "* Convert this to a spark data frame\n",
    "\n",
    "* We are going to treat the Power_Zone_3 variable as our response variable.\n",
    "\n",
    "* We can use all of the other variables as predictors. (Imagine we know that the Power_Zone_3 reading is going to go offline in the future and we need to be able to predict that value appropriately.)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d9f7a0de-bca4-4293-a504-c684f78cef6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Using incubator modules: jdk.incubator.vector\n",
      "Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties\n",
      "Setting default log level to \"WARN\".\n",
      "To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).\n",
      "26/04/30 12:53:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable\n",
      "26/04/30 12:53:13 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.\n",
      "26/04/30 12:53:13 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.\n",
      "26/04/30 12:53:13 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.\n",
      "26/04/30 12:53:13 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Spark DataFrame Schema:\n",
      "root\n",
      " |-- Temperature: double (nullable = true)\n",
      " |-- Humidity: double (nullable = true)\n",
      " |-- Wind_Speed: double (nullable = true)\n",
      " |-- General_Diffuse_Flows: double (nullable = true)\n",
      " |-- Diffuse_Flows: double (nullable = true)\n",
      " |-- Power_Zone_1: double (nullable = true)\n",
      " |-- Power_Zone_2: double (nullable = true)\n",
      " |-- label: double (nullable = true)\n",
      " |-- Month: integer (nullable = true)\n",
      " |-- Hour: integer (nullable = true)\n",
      "\n",
      "\n",
      "First 5 rows of Spark DataFrame:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[Stage 0:>                                                          (0 + 1) / 1]\r"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+-----------+--------+----------+---------------------+-------------+------------+------------+-----------+-----+----+\n",
      "|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|      label|Month|Hour|\n",
      "+-----------+--------+----------+---------------------+-------------+------------+------------+-----------+-----+----+\n",
      "|      6.559|    73.8|     0.083|                0.051|        0.119|  34055.6962| 16128.87538|20240.96386|    1|   0|\n",
      "|      6.414|    74.5|     0.083|                 0.07|        0.085| 29814.68354| 19375.07599|20131.08434|    1|   0|\n",
      "|      6.313|    74.5|      0.08|                0.062|          0.1| 29128.10127| 19006.68693|19668.43373|    1|   0|\n",
      "|      6.121|    75.0|     0.083|                0.091|        0.096| 28228.86076| 18361.09422|18899.27711|    1|   0|\n",
      "|      5.921|    75.7|     0.081|                0.048|        0.085|  27335.6962| 17872.34043|18442.40964|    1|   0|\n",
      "+-----------+--------+----------+---------------------+-------------+------------+------------+-----------+-----+----+\n",
      "only showing top 5 rows\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "                                                                                \r"
     ]
    }
   ],
   "source": [
    "# Initialize SparkSession\n",
    "spark = SparkSession.builder.appName(\"PowerDataProcessing\").getOrCreate()\n",
    "\n",
    "# Define the URL for the dataset\n",
    "data_url = \"https://www4.stat.ncsu.edu/~online/datasets/power_ml_data.csv\"\n",
    "\n",
    "# Read the data into a pandas DataFrame, using the first row as headers\n",
    "pd_df = pd.read_csv(data_url, header=0)\n",
    "\n",
    "# Define the Spark schema based on the provided headers\n",
    "spark_schema = StructType([\n",
    "    StructField(\"Temperature\", DoubleType(), True),\n",
    "    StructField(\"Humidity\", DoubleType(), True),\n",
    "    StructField(\"Wind_Speed\", DoubleType(), True),\n",
    "    StructField(\"General_Diffuse_Flows\", DoubleType(), True),\n",
    "    StructField(\"Diffuse_Flows\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_1\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_2\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_3\", DoubleType(), True),\n",
    "    StructField(\"Month\", IntegerType(), True),\n",
    "    StructField(\"Hour\", IntegerType(), True)\n",
    "])\n",
    "\n",
    "# Convert pandas DataFrame to Spark DataFrame\n",
    "spark_df = spark.createDataFrame(pd_df, schema=spark_schema)\n",
    "\n",
    "# Rename Power_Zone_3 to 'label' as it is our response variable\n",
    "spark_df = spark_df.withColumnRenamed(\"Power_Zone_3\", \"label\")\n",
    "\n",
    "# Display schema and first few rows to verify\n",
    "print(\"Spark DataFrame Schema:\")\n",
    "spark_df.printSchema()\n",
    "\n",
    "print(\"\\nFirst 5 rows of Spark DataFrame:\")\n",
    "spark_df.show(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "78bb68d0-4069-4d2d-ad2a-1116e74add3a",
   "metadata": {},
   "source": [
    "Part 2: Elastic Model Initial Pipeline Set Up\n",
    "\n",
    "We want to fit an elastic net model using CV (no training/test split, just using CV on the data we’ve read\n",
    "in) with the steps below.\n",
    "\n",
    "The transformations below should each use an MLlib function that can be put into a pipeline\n",
    "\n",
    "  * The Hour column is likely not stored as a DoubleType. If it is not, use an SQL transformer to cast the variable as a DoubleType\n",
    "\n",
    "  * Binarize the Hour column based on the column being less than 6.5 or not (night vs day essentially)\n",
    "\n",
    "  * One-hot encode the Month column\n",
    "\n",
    "  * Run a PCA fit on the Temperature, Humidity, Wind_Speed, General_Diffuse_Flows, and Diffuse_Flows columns.\n",
    "\n",
    "    * To do this, I first used a VectorAssembler() call to place these variables in a column together for use with the PCA() estimator.\n",
    "\n",
    "    * Once fitted, then you’ll have a PCA transformer we’ll use in our pipeline.\n",
    "\n",
    "    * We’ll use two PCs in our transformation.\n",
    "\n",
    "* Rename your response variable as label\n",
    "\n",
    "* Use VectorAssembler() to put your predictors into a features. Use the:\n",
    "\n",
    "  * two fitted PCA features\n",
    "\n",
    "  * binary Hour variable\n",
    "\n",
    "  * Power_Zone_1\n",
    "\n",
    "  * Power_Zone_2\n",
    "\n",
    "  * Month indicator variables\n",
    "\n",
    "* This ends the pipeline of transformations!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "231308b2-9c95-4a12-97ec-567d794e3f33",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pipeline stages defined successfully.\n"
     ]
    }
   ],
   "source": [
    "# Step 1: Cast Hour column to DoubleType if not already\n",
    "sql_transformer_hour = SQLTransformer(statement=\"SELECT *, CAST(Hour AS DOUBLE) AS Hour_Double FROM __THIS__\")\n",
    "\n",
    "# Step 2: Binarize the Hour column (Night vs Day)\n",
    "binarizer = Binarizer(threshold=6.5, inputCol=\"Hour_Double\", outputCol=\"Hour_Binary\")\n",
    "\n",
    "# Step 3: One-hot encode the Month column\n",
    "month_indexer = StringIndexer(inputCol=\"Month\", outputCol=\"Month_Indexed\")\n",
    "\n",
    "# Then, OneHotEncoder to convert the indexed column to one-hot vectors\n",
    "month_encoder = OneHotEncoder(inputCols=[\"Month_Indexed\"], outputCols=[\"Month_OneHot\"])\n",
    "\n",
    "# Step 4: PCA on Temperature, Humidity, Wind_Speed, General_Diffuse_Flows, and Diffuse_Flows\n",
    "pca_input_cols = [\"Temperature\", \"Humidity\", \"Wind_Speed\", \"General_Diffuse_Flows\", \"Diffuse_Flows\"]\n",
    "vector_assembler_pca = VectorAssembler(inputCols=pca_input_cols, outputCol=\"pca_features\")\n",
    "\n",
    "# Apply PCA to reduce dimensions to 2 principal components\n",
    "pca = PCA(k=2, inputCol=\"pca_features\", outputCol=\"principal_components\")\n",
    "\n",
    "# Step 5: Final VectorAssembler to put all predictors into a 'features' vector\n",
    "# Use the two fitted PCA features, binary Hour, Power_Zone_1, Power_Zone_2, and Month indicator variables\n",
    "final_features_assembler = VectorAssembler(\n",
    "    inputCols=[\n",
    "        \"principal_components\",\n",
    "        \"Hour_Binary\",\n",
    "        \"Power_Zone_1\",\n",
    "        \"Power_Zone_2\",\n",
    "        \"Month_OneHot\"\n",
    "    ],\n",
    "    outputCol=\"features\"\n",
    ")\n",
    "\n",
    "# Step 6: Define the Linear Regression model\n",
    "lr = LinearRegression(featuresCol=\"features\", labelCol=\"label\", predictionCol=\"prediction\")\n",
    "\n",
    "# Create the pipeline\n",
    "pipeline = Pipeline(stages=[\n",
    "    sql_transformer_hour,\n",
    "    binarizer,\n",
    "    month_indexer,\n",
    "    month_encoder,\n",
    "    vector_assembler_pca,\n",
    "    pca,\n",
    "    final_features_assembler,\n",
    "    lr # Add the Linear Regression model as the final stage of the pipeline\n",
    "])\n",
    "\n",
    "print(\"Pipeline stages defined successfully.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "faa46c36-0675-4dc8-88d1-e185266279ea",
   "metadata": {},
   "source": [
    "Part 3: Fitting & Printing the Model\n",
    "\n",
    "* Now you’ll then use the CrossValidator() function and the LinearRegression() function to fit an elastic net model.\n",
    "\n",
    "  * You should do the following grid for the regParam and elasticNetParam: All combinations of\n",
    "\n",
    "    * regParam: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1\n",
    "\n",
    "    * elasticNetParam: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1\n",
    "\n",
    "* Now fit the model using 5-fold CV with rmse as your criterion!\n",
    "\n",
    "* Report the optimal values chosen for the tuning parameters\n",
    "\n",
    "* Report the CV error\n",
    "\n",
    "* Report the training set RMSE (as done in the notes) by using your fitted model as a transformer and evaluating on the entire training set\n",
    "\n",
    "* Take the outputted transformations from the model (the predictions) and create a residual column (label - prediction). The .withColumn() method is handy here. Print out a data frame with these residuals, the label column, and the predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "369b273e-ecb3-4008-a709-ad426a9bb443",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting the model using CrossValidator...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "26/04/30 12:29:25 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.\n",
      "26/04/30 12:29:26 WARN Instrumentation: [6d27cfb4] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:29 WARN Instrumentation: [0289fe96] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:31 WARN Instrumentation: [673e76de] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:33 WARN Instrumentation: [ea633f71] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:34 WARN Instrumentation: [ff262512] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:35 WARN Instrumentation: [504962c7] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:36 WARN Instrumentation: [2d4795d1] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:38 WARN Instrumentation: [975709b9] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:39 WARN Instrumentation: [c95c99f2] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:40 WARN Instrumentation: [1ff60e19] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:29:41 WARN Instrumentation: [743fafe3] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:21 WARN Instrumentation: [14ced0fb] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:23 WARN Instrumentation: [1555c5a3] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:24 WARN Instrumentation: [04139fe8] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:25 WARN Instrumentation: [a974fea6] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:26 WARN Instrumentation: [9c229850] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:27 WARN Instrumentation: [06762453] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:28 WARN Instrumentation: [e22d5a0e] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:29 WARN Instrumentation: [0f9498a5] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:30 WARN Instrumentation: [b6eb9816] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:31 WARN Instrumentation: [f5a55456] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:32:32 WARN Instrumentation: [82b15fd9] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:23 WARN Instrumentation: [418ec6f1] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:24 WARN Instrumentation: [f79f8d80] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:25 WARN Instrumentation: [a18ad02d] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:26 WARN Instrumentation: [353b5eb8] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:27 WARN Instrumentation: [a1a3e544] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:28 WARN Instrumentation: [0121ee04] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:29 WARN Instrumentation: [5cbd636e] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:30 WARN Instrumentation: [06f19d98] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:31 WARN Instrumentation: [1405444f] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:32 WARN Instrumentation: [e08ff2a3] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:34:33 WARN Instrumentation: [dffe3bce] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:23 WARN Instrumentation: [b1c64e6b] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:24 WARN Instrumentation: [763a778b] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:25 WARN Instrumentation: [d6110f7a] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:26 WARN Instrumentation: [be04d029] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:27 WARN Instrumentation: [138cda97] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:28 WARN Instrumentation: [e44beb7a] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:29 WARN Instrumentation: [245954d5] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:30 WARN Instrumentation: [77d851d1] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:31 WARN Instrumentation: [380fac94] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:32 WARN Instrumentation: [f2f4abb5] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:36:33 WARN Instrumentation: [0a31a296] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:34 WARN Instrumentation: [04dbc0c0] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:36 WARN Instrumentation: [07134790] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:37 WARN Instrumentation: [43afe70d] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:38 WARN Instrumentation: [83372193] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:39 WARN Instrumentation: [08868435] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:40 WARN Instrumentation: [b01e2cef] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:41 WARN Instrumentation: [bd4c7448] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:42 WARN Instrumentation: [02fab67b] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:43 WARN Instrumentation: [92dc8953] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:44 WARN Instrumentation: [ec2d9780] regParam is zero, which might cause numerical instability and overfitting.\n",
      "26/04/30 12:38:45 WARN Instrumentation: [57d653c5] regParam is zero, which might cause numerical instability and overfitting.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model fitting complete.\n",
      "Could not find LinearRegression stage in the best model.\n",
      "\n",
      "Cross-validation RMSE (best model): 2147.5891325226876\n",
      "Training set RMSE: 2147.097322400667\n",
      "\n",
      "DataFrame with Label, Prediction, and Residuals:\n",
      "+-----------+------------------+------------------+\n",
      "|      label|        prediction|          residual|\n",
      "+-----------+------------------+------------------+\n",
      "|20240.96386|20879.293929772837|-638.3300697728373|\n",
      "|20131.08434|18659.581224684986|1471.5031153150157|\n",
      "|19668.43373|18204.118378530166|1464.3153514698352|\n",
      "|18899.27711|17590.065188636432| 1309.211921363567|\n",
      "|18442.40964|16996.736644024797|1445.6729959752047|\n",
      "|18130.12048| 16517.14980719943| 1612.970672800573|\n",
      "|17945.06024|16092.738824696906| 1852.321415303093|\n",
      "|17459.27711|15722.205354351358|1737.0717556486416|\n",
      "|17025.54217| 15270.58168727468|1754.9604827253206|\n",
      "|16794.21687|14937.899896525745| 1856.316973474255|\n",
      "+-----------+------------------+------------------+\n",
      "only showing top 10 rows\n"
     ]
    }
   ],
   "source": [
    "# The Linear Regression model is already part of the pipeline defined in the previous cell.\n",
    "# We need to retrieve that instance to correctly define the ParamGridBuilder.\n",
    "lr_from_pipeline = None\n",
    "for stage in pipeline.getStages():\n",
    "    if isinstance(stage, LinearRegression):\n",
    "        lr_from_pipeline = stage\n",
    "        break\n",
    "\n",
    "if lr_from_pipeline is None:\n",
    "    raise ValueError(\"LinearRegression stage not found in the pipeline. Please ensure the pipeline in the previous cell is correctly defined and executed with a LinearRegression model.\")\n",
    "\n",
    "# Define the parameter grid for regParam and elasticNetParam\n",
    "paramGrid = ParamGridBuilder() \\\n",
    "    .addGrid(lr_from_pipeline.regParam, [0.0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1.0]) \\\n",
    "    .addGrid(lr_from_pipeline.elasticNetParam, [0.0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1.0]) \\\n",
    "    .build()\n",
    "\n",
    "# Create a RegressionEvaluator for RMSE\n",
    "evaluator = RegressionEvaluator(labelCol=\"label\", predictionCol=\"prediction\", metricName=\"rmse\")\n",
    "\n",
    "# Create the CrossValidator\n",
    "cv = CrossValidator(\n",
    "    estimator=pipeline, # Use the previously defined pipeline as the estimator\n",
    "    estimatorParamMaps=paramGrid,\n",
    "    evaluator=evaluator,\n",
    "    numFolds=5, \n",
    "    seed=42 \n",
    ")\n",
    "\n",
    "print(\"Fitting the model using CrossValidator...\")\n",
    "# Fit the model to the spark_df\n",
    "cvModel = cv.fit(spark_df)\n",
    "\n",
    "print(\"Model fitting complete.\")\n",
    "\n",
    "# --- Reporting Results ---\n",
    "\n",
    "# The best model from CrossValidator is stored in cvModel.bestModel\n",
    "best_pipeline_model = cvModel.bestModel\n",
    "\n",
    "# Find the LinearRegressionModel stage in the best pipeline model\n",
    "best_lr_model = None\n",
    "for stage in best_pipeline_model.stages:\n",
    "    if isinstance(stage, LinearRegression):\n",
    "        best_lr_model = stage\n",
    "        break\n",
    "\n",
    "if best_lr_model:\n",
    "    print(f\"\\nOptimal regParam: {best_lr_model.getRegParam()}\")\n",
    "    print(f\"Optimal elasticNetParam: {best_lr_model.getElasticNetParam()}\")\n",
    "else:\n",
    "    print(\"Could not find LinearRegression stage in the best model.\")\n",
    "\n",
    "# Report the CV error (average RMSE from cross-validation)\n",
    "best_rmse = min(cvModel.avgMetrics)\n",
    "print(f\"\\nCross-validation RMSE (best model): {best_rmse}\")\n",
    "\n",
    "# Report the training set RMSE\n",
    "transformed_df = cvModel.transform(spark_df)\n",
    "\n",
    "training_rmse = evaluator.evaluate(transformed_df)\n",
    "print(f\"Training set RMSE: {training_rmse}\")\n",
    "\n",
    "# Take the outputted transformations (predictions) and create a residual column\n",
    "residuals_df = transformed_df.withColumn(\"residual\", col(\"label\") - col(\"prediction\"))\n",
    "\n",
    "print(\"\\nDataFrame with Label, Prediction, and Residuals:\")\n",
    "residuals_df.select(\"label\", \"prediction\", \"residual\").show(10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f20bcb2f-3b41-4943-99ce-c38c558f7059",
   "metadata": {},
   "source": [
    "Streaming Part (40 pts)\n",
    "\n",
    "There is another file available at: https://www4.stat.ncsu.edu/~online/datasets/power_streaming_data.csv\n",
    "Download this file and store it where your .py file you’ll create can find it. We’ll be randomly sampling rows\n",
    "from this to output to .csv files that you’ll be reading in."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c13a8093-8818-4772-926b-cec58bab5b5d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Streaming DataFrame Schema:\n",
      "root\n",
      " |-- Temperature: double (nullable = true)\n",
      " |-- Humidity: double (nullable = true)\n",
      " |-- Wind_Speed: double (nullable = true)\n",
      " |-- General_Diffuse_Flows: double (nullable = true)\n",
      " |-- Diffuse_Flows: double (nullable = true)\n",
      " |-- Power_Zone_1: double (nullable = true)\n",
      " |-- Power_Zone_2: double (nullable = true)\n",
      " |-- Power_Zone_3: double (nullable = true)\n",
      " |-- Month: integer (nullable = true)\n",
      " |-- Hour: integer (nullable = true)\n",
      "\n",
      "First 5 rows of Streaming DataFrame:\n",
      "+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+\n",
      "|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Power_Zone_3|Month|Hour|\n",
      "+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+\n",
      "|      4.805|    76.2|     0.081|                0.059|        0.134| 20421.26582| 12908.20669| 14590.84337|    1|   3|\n",
      "|      4.212|    78.3|     0.081|                0.117|        0.082| 21393.41772| 13575.68389|  14862.6506|    1|   5|\n",
      "|      4.304|    76.0|     0.082|                0.048|        0.152| 19983.79747| 12342.85714| 13492.04819|    1|   7|\n",
      "|      4.489|    74.3|     0.082|                0.081|        0.119| 18167.08861| 11551.36778| 11600.96386|    1|   7|\n",
      "|      4.509|    74.5|     0.084|                6.643|        6.494| 19837.97468| 11945.28875| 11178.79518|    1|   8|\n",
      "+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+\n",
      "only showing top 5 rows\n"
     ]
    }
   ],
   "source": [
    "# Define the schema for the streaming data\n",
    "spark_schema_streaming = StructType([\n",
    "    StructField(\"Temperature\", DoubleType(), True),\n",
    "    StructField(\"Humidity\", DoubleType(), True),\n",
    "    StructField(\"Wind_Speed\", DoubleType(), True),\n",
    "    StructField(\"General_Diffuse_Flows\", DoubleType(), True),\n",
    "    StructField(\"Diffuse_Flows\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_1\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_2\", DoubleType(), True),\n",
    "    StructField(\"Power_Zone_3\", DoubleType(), True),\n",
    "    StructField(\"Month\", IntegerType(), True),\n",
    "    StructField(\"Hour\", IntegerType(), True)\n",
    "])\n",
    "\n",
    "# Define the path to the streaming data file\n",
    "streaming_data_path = \"Power_Storage/power_streaming_data.csv\"\n",
    "\n",
    "# Read the data into a Spark DataFrame\n",
    "streaming_df = spark.read.csv(\n",
    "    streaming_data_path,\n",
    "    header=True,\n",
    "    schema=spark_schema_streaming\n",
    ")\n",
    "\n",
    "print(\"Streaming DataFrame Schema:\")\n",
    "streaming_df.printSchema()\n",
    "\n",
    "print(\"First 5 rows of Streaming DataFrame:\")\n",
    "streaming_df.show(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b6ca367-9802-4ab6-9bcc-26ec8dbf15c0",
   "metadata": {},
   "source": [
    "Part 1: Reading a Stream\n",
    "\n",
    "* We’re going to read in a stream in the form of .csv files. Create a folder where you will be sending your .csv files.\n",
    "\n",
    "* Setup the schema for the stream (you can use the schema from the original data as we did in hw 10)\n",
    "\n",
    "* Set up the readStream. Be sure to add header = True as you’ll likely be outputting files with a header and we don’t need to read that in."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1cf6b8eb-1359-442f-953d-5450b57d2d86",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Created streaming input directory: Power_Storage/stream_data_input\n",
      "Spark Structured Stream configured to read from:\n",
      "  Directory: Power_Storage/stream_data_input\n",
      "root\n",
      " |-- Temperature: double (nullable = true)\n",
      " |-- Humidity: double (nullable = true)\n",
      " |-- Wind_Speed: double (nullable = true)\n",
      " |-- General_Diffuse_Flows: double (nullable = true)\n",
      " |-- Diffuse_Flows: double (nullable = true)\n",
      " |-- Power_Zone_1: double (nullable = true)\n",
      " |-- Power_Zone_2: double (nullable = true)\n",
      " |-- Power_Zone_3: double (nullable = true)\n",
      " |-- Month: integer (nullable = true)\n",
      " |-- Hour: integer (nullable = true)\n",
      "\n",
      "  Schema: None\n",
      "Stream initialized successfully.\n"
     ]
    }
   ],
   "source": [
    "# 1. Create a folder where you will be sending your .csv files\n",
    "#    This will be the input directory for our Spark Structured Stream\n",
    "streaming_input_dir = \"Power_Storage/stream_data_input\"\n",
    "if not os.path.exists(streaming_input_dir):\n",
    "    os.makedirs(streaming_input_dir)\n",
    "    print(f\"Created streaming input directory: {streaming_input_dir}\")\n",
    "else:\n",
    "    print(f\"Streaming input directory already exists: {streaming_input_dir}\")\n",
    "\n",
    "# 2. Set up the readStream\n",
    "# We'll monitor the streaming_input_dir for new CSV files\n",
    "stream_df = spark.readStream \\\n",
    "    .format(\"csv\") \\\n",
    "    .option(\"header\", \"true\") \\\n",
    "    .schema(spark_schema_streaming) \\\n",
    "    .load(streaming_input_dir)\n",
    "\n",
    "print(\"Spark Structured Stream configured to read from:\")\n",
    "print(f\"  Directory: {streaming_input_dir}\")\n",
    "print(f\"  Schema: {stream_df.printSchema()}\")\n",
    "print(\"Stream initialized successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6fd8c95-2c3d-4141-a079-7a0f3b6ba623",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pySpark3",
   "language": "python",
   "name": "pyspark3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
